let data = {
    categories: {
        zubehor: {
            products: [
                {name: 'AS-301', description: 'Bad-Accessoire', category: 'zubehor', price: 16.8, imgURL: '../images/AS-301.gif'},
                {name: 'AS-302', description: 'Bad-Accessoire', category: 'zubehor', price: 10.8, imgURL: '../images/as-302.jpg'},
                {name: 'AS-303', description: 'Bad-Accessoire', category: 'zubehor', price: 9.6, imgURL: '../images/AS-303.jpg'},
                {name: 'AS-304', description: 'Bad-Accessoire', category: 'zubehor', price: 8.88, imgURL: '../images/AS-304.jpg'},
                {name: 'AS-305', description: 'Bad-Accessoire', category: 'zubehor', price: 10.8, imgURL: '../images/AS-305.gif'},
                {name: 'AS-316', description: 'Bad-Accessoire', category: 'zubehor', price: 24, imgURL: '../images/AS-316.jpg'},
                {name: 'AS-317', description: 'Bad-Accessoire', category: 'zubehor', price: 20.4, imgURL: '../images/AS-317.jpg'},
                {name: 'AS-319', description: 'Bad-Accessoire', category: 'zubehor', price: 19.2, imgURL: '../images/AS-319.jpg'},
                {name: 'AS-320', description: 'Bad-Accessoire', category: 'zubehor', price: 21.6, imgURL: '../images/AS-320.jpg'},
                {name: 'AS-321', description: 'Bad-Accessoire', category: 'zubehor', price: 19.2, imgURL: '../images/AS-321.jpg'},
                {name: 'AS-322', description: 'Bad-Accessoire', category: 'zubehor', price: 22.8, imgURL: '../images/AS-322.jpg'},
                {name: 'AS-323', description: 'Bad-Accessoire', category: 'zubehor', price: 13.2, imgURL: '../images/AS-323.jpg'},
                {name: 'AS-324', description: 'Bad-Accessoire', category: 'zubehor', price: 12.96, imgURL: '../images/AS-324.jpg'},
                {name: 'AS-325', description: 'Bad-Accessoire', category: 'zubehor', price: 20.4, imgURL: '../images/AS-325.jpg'},
                {name: 'AS-326', description: 'Bad-Accessoire', category: 'zubehor', price: 18.48, imgURL: '../images/AS-326.jpg'},
                {name: 'AS-328', description: 'Bad-Accessoire', category: 'zubehor', price: 19.92, imgURL: '../images/AS-328.jpg'},
                {name: 'AS-329', description: 'Bad-Accessoire', category: 'zubehor', price: 19.68, imgURL: '../images/AS-329.jpg'},
                {name: 'AS-330', description: 'Bad-Accessoire', category: 'zubehor', price: 26.4, imgURL: '../images/AS-330.jpg'},
                {name: 'AS-331', description: 'Bad-Accessoire', category: 'zubehor', price: 30, imgURL: '../images/AS-331.jpg'},
                {name: 'AS-332', description: 'Bad-Accessoire', category: 'zubehor', price: 22.08, imgURL: '../images/AS-332.jpg'},
                {name: 'AS-333', description: 'Bad-Accessoire', category: 'zubehor', price: 31.44, imgURL: '../images/AS-333.jpg'},
                {name: 'AS-334', description: 'Bad-Accessoire', category: 'zubehor', price: 23.28, imgURL: '../images/AS-334.jpg'},
                {name: 'AS-335', description: 'Bad-Accessoire', category: 'zubehor', price: 16.08, imgURL: '../images/AS-335.jpg'},
                {name: 'AS-337', description: 'Bad-Accessoire', category: 'zubehor', price: 36, imgURL: '../images/AS-337.jpg'},
                {name: 'AS-338', description: 'Bad-Accessoire', category: 'zubehor', price: 15.48, imgURL: '../images/AS-338.jpg'},
                {name: 'AS-318', description: 'Bad-Accessoire', category: 'zubehor', price: 19.92, imgURL: '../images/AS-318.jpg'},
                {name: 'AS-401', description: 'Bad-Accessoire', category: 'zubehor', price: 14.88, imgURL: '../images/AS-401.jpg'},
                {name: 'AS-402', description: 'Bad-Accessoire', category: 'zubehor', price: 11.64, imgURL: '../images/AS-402.jpg'},
                {name: 'AS-403', description: 'Bad-Accessoire', category: 'zubehor', price: 10.85, imgURL: '../images/AS-403.jpg'},
                {name: 'AS-404', description: 'Bad-Accessoire', category: 'zubehor', price: 11.28, imgURL: '../images/AS-404.jpg'},
                {name: 'AS-409', description: 'Bad-Accessoire', category: 'zubehor', price: 14.88, imgURL: '../images/AS-409.jpg'},
                {name: 'AS-410', description: 'Bad-Accessoire', category: 'zubehor', price: 20.16, imgURL: '../images/AS-410.jpg'},
                {name: 'AS-412', description: 'Bad-Accessoire', category: 'zubehor', price: 16.32, imgURL: '../images/AS-412.jpg'},
                {name: 'AS-416', description: 'Bad-Accessoire', category: 'zubehor', price: 24.36, imgURL: '../images/AS-416.jpg'},
                {name: 'AS-417', description: 'Bad-Accessoire', category: 'zubehor', price: 19.68, imgURL: '../images/AS-417.jpg'},
                {name: 'AS-420', description: 'Bad-Accessoire', category: 'zubehor', price: 26.4, imgURL: '../images/AS-420.jpg'},
                {name: 'AS-421', description: 'Bad-Accessoire', category: 'zubehor', price: 21.84, imgURL: '../images/AS-421.jpg'},
                {name: 'AS-424', description: 'Bad-Accessoire', category: 'zubehor', price: 19.92, imgURL: '../images/AS-424.jpg'},
                {name: 'AS-426', description: 'Bad-Accessoire', category: 'zubehor', price: 20.16, imgURL: '../images/AS-426.jpg'},
                {name: 'AS-501', description: 'Bad-Accessoire', category: 'zubehor', price: 18, imgURL: '../images/AS-501.jpg'},
                {name: 'AS-503', description: 'Bad-Accessoire', category: 'zubehor', price: 12.72, imgURL: '../images/AS-503.jpg'},
                {name: 'AS-504', description: 'Bad-Accessoire', category: 'zubehor', price: 13.68, imgURL: '../images/AS-504.jpg'},
                {name: 'AS-505', description: 'Bad-Accessoire', category: 'zubehor', price: 20.16, imgURL: '../images/AS-505.jpg'},
                {name: 'AS-508', description: 'Bad-Accessoire', category: 'zubehor', price: 13.2, imgURL: '../images/AS-508.jpg'},
                {name: 'AS-509', description: 'Bad-Accessoire', category: 'zubehor', price: 14.88, imgURL: '../images/AS-509.jpg'},
                {name: 'AS-510', description: 'Bad-Accessoire', category: 'zubehor', price: 24.24, imgURL: '../images/AS-510.jpg'},
                {name: 'AS-511', description: 'Bad-Accessoire', category: 'zubehor', price: 23.04, imgURL: '../images/AS-511.jpg'},
                {name: 'AS-512', description: 'Bad-Accessoire', category: 'zubehor', price: 17.52, imgURL: '../images/AS-512.jpg'},
                {name: 'AS-513', description: 'Bad-Accessoire', category: 'zubehor', price: 36.48, imgURL: '../images/AS-513.jpg'},
                {name: 'AS-514', description: 'Bad-Accessoire', category: 'zubehor', price: 22.32, imgURL: '../images/AS-514.jpg'},
                {name: 'AS-515', description: 'Bad-Accessoire', category: 'zubehor', price: 22.08, imgURL: '../images/AS-515.jpg'},
                {name: 'AS-516', description: 'Bad-Accessoire', category: 'zubehor', price: 27.6, imgURL: '../images/AS-516.jpg'},
                {name: 'AS-517', description: 'Bad-Accessoire', category: 'zubehor', price: 40.8, imgURL: '../images/AS-517.jpg'},
                {name: 'AS-521', description: 'Bad-Accessoire', category: 'zubehor', price: 19.92, imgURL: '../images/AS-521.jpg'},
                {name: 'AS-523', description: 'Bad-Accessoire', category: 'zubehor', price: 16.08, imgURL: '../images/AS-523.jpg'},
                {name: 'AS-524', description: 'Bad-Accessoire', category: 'zubehor', price: 15.36, imgURL: '../images/AS-524.jpg'},
                {name: 'AS-327', description: 'Bad-Accessoire', category: 'zubehor', price: 26.82, imgURL: '../images/AS-327.jpg'},
                {name: 'SH-286', description: 'Bad-Accessoire', category: 'zubehor', price: 10.5, imgURL: '../images/SH-286.jpg'},
                {name: '95A-6', description: 'Bad-Accessoires aus Edelstahl', category: 'zubehor', price: 60, imgURL: '../images/95A-6.jpg'},
                {name: '98A-6', description: 'Bad-Accessoires aus Edelstahl', category: 'zubehor', price: 96, imgURL: '../images/98A-6.jpg'},
                {name: 'A-806', description: 'Bad-Accessoires aus Edelstahl', category: 'zubehor', price: 88.8, imgURL: '../images/A-806.jpg'},
                {name: 'AS-306', description: 'Bad-Accessoires aus Edelstahl', category: 'zubehor', price: 67.2, imgURL: '../images/AS-306.gif'},
                {name: 'A-106', description: 'Bad-Accessoires aus Edelstahl, Glänzend', category: 'zubehor', price: 112.8, imgURL: '../images/A-106.jpg'},
                {name: '69-6', description: 'Bad-Accessoires aus Edelstahl, Schwarz', category: 'zubehor', price: 93.6, imgURL: '../images/69-6.jpg'},
                {name: 'A-906', description: 'Bad-Accessoires aus Edelstahl, Schwarz', category: 'zubehor', price: 93.6, imgURL: '../images/A-906.jpg'},
                {name: '68-6', description: 'Bad-Accessoires aus Edelstahl, Schwarz-gold', category: 'zubehor', price: 91.2, imgURL: '../images/68-6.jpg'},
            ]
        },
        bidets: {
            products: [
                {name: 'SH-157', description: 'Bidet', category: 'bidets', price: 15, imgURL: '../images/SH-157.jpg'},
                {name: 'SH-245', description: 'Bidet', category: 'bidets', price: 45, imgURL: '../images/SH-245.jpg'},
                {name: 'SH-285', description: 'Bidet', category: 'bidets', price: 30, imgURL: '../images/SH-285.jpg'},
                {name: 'SH-293', description: 'Bidet', category: 'bidets', price: 63.9, imgURL: '../images/SH-293.jpg'},
                {name: 'SH-294', description: 'Bidet', category: 'bidets', price: 73.5, imgURL: '../images/SH-294.jpg'},
                {name: 'SH-295', description: 'Bidet', category: 'bidets', price: 48, imgURL: '../images/SH-295.jpg'},
                {name: 'SH-325', description: 'Bidet', category: 'bidets', price: 42, imgURL: '../images/SH-325.jpg'},
                {name: 'SH-345', description: 'Bidet', category: 'bidets', price: 65.7, imgURL: '../images/SH-345.jpg'},
            ]
        },
        duschabflusse: {
            products: [
                {name: 'C01-B', description: 'Bodenablauf', category: 'duschabflusse', price: 26.4, imgURL: '../images/C01-B.jpg'},
                {name: 'C01-G', description: 'Bodenablauf', category: 'duschabflusse', price: 26.4, imgURL: '../images/C01-G.jpg'},
                {name: 'C01-N', description: 'Bodenablauf', category: 'duschabflusse', price: 26.4, imgURL: '../images/C01-N.jpg'},
                {name: 'C03-G', description: 'Bodenablauf', category: 'duschabflusse', price: 24, imgURL: '../images/C03-G.jpg'},
                {name: 'C06-G', description: 'Bodenablauf', category: 'duschabflusse', price: 22.8, imgURL: '../images/C06-G (1).jpg'},
                {name: 'C07-B', description: 'Bodenablauf', category: 'duschabflusse', price: 23.52, imgURL: '../images/C07-B.jpg'},
                {name: 'D08-B', description: 'Bodenablauf', category: 'duschabflusse', price: 24, imgURL: '../images/D08-B.jpg'},
                {name: 'D08-N', description: 'Bodenablauf', category: 'duschabflusse', price: 23.52, imgURL: '../images/D08-N.jpg'},
                {name: 'F01-B', description: 'Bodenablauf', category: 'duschabflusse', price: 28.08, imgURL: '../images/F01-B.jpg'},
                {name: 'F01-N', description: 'Bodenablauf', category: 'duschabflusse', price: 28.8, imgURL: '../images/F01-N.jpg'},
                {name: 'F01-Q', description: 'Bodenablauf', category: 'duschabflusse', price: 26.4, imgURL: '../images/F01-Q (2).jpg'},
                {name: 'F03-B', description: 'Bodenablauf', category: 'duschabflusse', price: 28.8, imgURL: '../images/F03-B.jpg'},
                {name: 'F03-G', description: 'Bodenablauf', category: 'duschabflusse', price: 33.6, imgURL: '../images/F03-G.jpg'},
                {name: 'F03-N', description: 'Bodenablauf', category: 'duschabflusse', price: 33.6, imgURL: '../images/F03-N.jpg'},
                {name: 'F03-Q', description: 'Bodenablauf', category: 'duschabflusse', price: 33.6, imgURL: '../images/F03-Q.jpg'},
                {name: 'F06-H', description: 'Bodenablauf', category: 'duschabflusse', price: 24, imgURL: '../images/F06-H.jpg'},
                {name: 'F07-G', description: 'Bodenablauf', category: 'duschabflusse', price: 32.4, imgURL: '../images/F07-G.jpg'},
                {name: 'F07-N', description: 'Bodenablauf', category: 'duschabflusse', price: 33.6, imgURL: '../images/F07-N.jpg'},
                {name: 'F10-B', description: 'Bodenablauf', category: 'duschabflusse', price: 28.8, imgURL: '../images/F10-B.jpg'},
                {name: 'F12-N', description: 'Bodenablauf', category: 'duschabflusse', price: 28.8, imgURL: '../images/F12-N.jpg'},
                {name: 'F13-G', description: 'Bodenablauf', category: 'duschabflusse', price: 26.8, imgURL: '../images/F13-G.jpg'},
                {name: 'F13-N', description: 'Bodenablauf', category: 'duschabflusse', price: 28.8, imgURL: '../images/F13-N.jpg'},
                {name: 'F13-Q', description: 'Bodenablauf', category: 'duschabflusse', price: 26.4, imgURL: '../images/F13-Q.jpg'},
                {name: 'F-200G', description: 'Bodenablauf', category: 'duschabflusse', price: 76.8, imgURL: '../images/F-200G.jpg'},
                {name: 'F-201N', description: 'Bodenablauf', category: 'duschabflusse', price: 79.5, imgURL: '../images/F-201N.jpg'},
                {name: 'F202B', description: 'Bodenablauf', category: 'duschabflusse', price: 80.1, imgURL: '../images/F202B.jpg'},
                {name: 'K297-B', description: 'Bodenablauf', category: 'duschabflusse', price: 59.7, imgURL: '../images/K297-B.jpg'},
                {name: 'W02-B', description: 'Bodenablauf', category: 'duschabflusse', price: 33, imgURL: '../images/W02-B.jpg'},
            ]
        },
        // duschkopf: {
        //     products: [
        //         {name: 'SH-107', description: 'Duschkopf', category: 'duschkopf', price: 6, imgURL: '../images/SH-107.jpg'},
        //         {name: 'SH-156', description: 'Duschkopf', category: 'duschkopf', price: 7.5, imgURL: '../images/SH-156.jpg'},
        //         {name: 'SH-315', description: 'Duschkopf', category: 'duschkopf', price: 6, imgURL: '../images/SH-315.jpg'},
        //         {name: 'SH-316', description: 'Duschkopf', category: 'duschkopf', price: 19.5, imgURL: '../images/SH-316.jpg'},
        //         {name: 'SH-317', description: 'Duschkopf', category: 'duschkopf', price: 28.5, imgURL: '../images/SH-317.jpg'},
        //     ]
        // },
        duschen: {
            products: [
                {name: 'SH-120', description: 'Duschset', category: 'duschen', price: 120, imgURL: '../images/SH-120.jpg'},
                {name: 'SH-121', description: 'Duschset', category: 'duschen', price: 114, imgURL: '../images/SH-121.jpg'},
                {name: 'SH-135', description: 'Duschset', category: 'duschen', price: 99, imgURL: '../images/SH-135.jpg'},
                {name: 'SH-136', description: 'Duschset', category: 'duschen', price: 117, imgURL: '../images/SH-136.jpg'},
                {name: 'SH-137', description: 'Duschset', category: 'duschen', price: 159, imgURL: '../images/SH-137.jpg'},
                {name: 'SH-152', description: 'Duschset', category: 'duschen', price: 168, imgURL: '../images/SH-152.jpg'},
                {name: 'SH-204', description: 'Duschset', category: 'duschen', price: 69, imgURL: '../images/SH-204.jpg'},
                {name: 'SH-217', description: 'Duschset', category: 'duschen', price: 240, imgURL: '../images/SH-217.jpg'},
                {name: 'SH-219', description: 'Duschset', category: 'duschen', price: 219, imgURL: '../images/SH-219.jpg'},
                {name: 'SH-220', description: 'Duschset', category: 'duschen', price: 201, imgURL: '../images/SH-220.jpg'},
                {name: 'SH-221', description: 'Duschset', category: 'duschen', price: 192, imgURL: '../images/SH-221.jpg'},
                {name: 'SH-222', description: 'Duschset', category: 'duschen', price: 180, imgURL: '../images/SH-222.jpg'},
                {name: 'SH-224', description: 'Duschset', category: 'duschen', price: 123, imgURL: '../images/SH-224.jpg'},
                {name: 'SH-225', description: 'Duschset', category: 'duschen', price: 129, imgURL: '../images/SH-225.jpg'},
                {name: 'SH-227', description: 'Duschset', category: 'duschen', price: 237, imgURL: '../images/SH-227.jpg'},
                {name: 'SH-246', description: 'Duschset', category: 'duschen', price: 63, imgURL: '../images/SH-246.jpg'},
                {name: 'SH-247', description: 'Duschset', category: 'duschen', price: 90, imgURL: '../images/SH-247.jpg'},
                {name: 'SH-248', description: 'Duschset', category: 'duschen', price: 75, imgURL: '../images/SH-248.jpg'},
                {name: 'SH-281', description: 'Duschset', category: 'duschen', price: 228, imgURL: '../images/SH-281.jpg'},
                {name: 'SH-282', description: 'Duschset', category: 'duschen', price: 234, imgURL: '../images/SH-282.jpg'},
                {name: 'SH-289', description: 'Duschset', category: 'duschen', price: 201, imgURL: '../images/SH-289.jpg'},
                {name: 'SH-299', description: 'Duschset', category: 'duschen', price: 192, imgURL: '../images/SH-299.jpg'},
                {name: 'SH-320', description: 'Duschset', category: 'duschen', price: 120, imgURL: '../images/SH-320.jpg'},
                {name: 'SH-336', description: 'Duschset', category: 'duschen', price: 120, imgURL: '../images/SH-336.jpg'},
                {name: 'SH-337', description: 'Duschset', category: 'duschen', price: 288, imgURL: '../images/SH-337.jpg'},
                {name: 'SH-349', description: 'Duschset', category: 'duschen', price: 138, imgURL: '../images/SH-349.jpg'},
                {name: 'SH-360', description: 'Duschset', category: 'duschen', price: 87, imgURL: '../images/SH-360.jpg'},
            ]
        },
        ersatzteile: {
            products: [
                {name: 'SH-119', description: 'Eckventil', category: 'ersatzteile', price: 6, imgURL: '../images/SH-119.jpg'},
                {name: 'SH-139', description: 'Eckventil', category: 'ersatzteile', price: 6, imgURL: '../images/SH-139.jpg'},
                {name: 'SH-319', description: 'Eckventil', category: 'ersatzteile', price: 16.5, imgURL: '../images/SH-319.jpg'},
                {name: 'SH-339', description: 'Eckventil', category: 'ersatzteile', price: 9.15, imgURL: '../images/SH-339.jpg'},
                {name: 'SH-341', description: 'Eckventil', category: 'ersatzteile', price: 9.6, imgURL: '../images/SH-341.jpg'},
                {name: 'SH-342', description: 'Eckventil', category: 'ersatzteile', price: 8.4, imgURL: '../images/SH-342.jpg'},
                {name: 'SH-343', description: 'Eckventil', category: 'ersatzteile', price: 10.2, imgURL: '../images/SH-343.jpg'},
            ]
        },
        // handtuchbügel: {
        //     products: [
        //         {name: 'HH-203', description: 'Handtuchbügel', category: 'handtuchbugel', price: 8.85, imgURL: '../images/HH-203.jpg'},
        //         {name: 'HH-204', description: 'Handtuchbügel', category: 'handtuchbugel', price: 11.82, imgURL: '../images/HH-204.jpg'},
        //         {name: 'HH-205', description: 'Handtuchbügel', category: 'handtuchbugel', price: 14.79, imgURL: '../images/HH-205.jpg'},
        //         {name: 'HH-206', description: 'Handtuchbügel', category: 'handtuchbugel', price: 17.73, imgURL: '../images/HH-206.jpg'},
        //     ]
        // },
        // wandwasserhahn: {
        //     products: [
        //         {name: 'SH-128', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 28.5, imgURL: '../images/SH-128.jpg'},
        //         {name: 'SH-129', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 54, imgURL: '../images/SH-129.jpg'},
        //         {name: 'SH-131', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 45, imgURL: '../images/SH-131.jpg'},
        //         {name: 'SH-143', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 63, imgURL: '../images/SH-143.gif'},
        //         {name: 'SH-150', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 60, imgURL: '../images/SH-150.jpg'},
        //         {name: 'SH-153', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 12, imgURL: '../images/SH-153.jpg'},
        //         {name: 'SH-154', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 24, imgURL: '../images/SH-154.jpg'},
        //         {name: 'SH-159', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 45, imgURL: '../images/SH-159.jpg'},
        //         {name: 'SH-167', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 18, imgURL: '../images/SH-167.jpg'},
        //         {name: 'SH-179', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 45, imgURL: '../images/SH-179.jpg'},
        //         {name: 'SH-201', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 45, imgURL: '../images/SH-201.jpg'},
        //         {name: 'SH-242', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 24, imgURL: '../images/SH-242.jpg'},
        //         {name: 'SH-250', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 33, imgURL: '../images/SH-250.jpg'},
        //         {name: 'SH-251', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 48, imgURL: '../images/SH-251.jpg'},
        //         {name: 'SH-254', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 30, imgURL: '../images/SH-254.jpg'},
        //         {name: 'SH-257', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 45, imgURL: '../images/SH-257.jpg'},
        //         {name: 'SH-259', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 54, imgURL: '../images/SH-259.jpg'},
        //         {name: 'SH-260', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 30, imgURL: '../images/SH-260.jpg'},
        //         {name: 'SH-263', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 34.5, imgURL: '../images/SH-263.jpg'},
        //         {name: 'SH-264', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 51, imgURL: '../images/SH-264.jpg'},
        //         {name: 'SH-265', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 37.5, imgURL: '../images/SH-265.jpg'},
        //         {name: 'SH-266', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 60, imgURL: '../images/SH-266.jpg'},
        //         {name: 'SH-268', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 36, imgURL: '../images/SH-268.jpg'},
        //         {name: 'SH-272', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 42, imgURL: '../images/SH-272.jpg'},
        //         {name: 'SH-298', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 59.7, imgURL: '../images/SH-298.jpg'},
        //         {name: 'SH-303', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 54.6, imgURL: '../images/SH-303.jpg'},
        //         {name: 'SH-304', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 36, imgURL: '../images/SH-304.jpg'},
        //         {name: 'SH-305', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 39, imgURL: '../images/SH-305.jpg'},
        //         {name: 'SH-306', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 34.5, imgURL: '../images/SH-306.jpg'},
        //         {name: 'SH-307', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 36, imgURL: '../images/SH-307.jpg'},
        //         {name: 'SH-310', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 66.9, imgURL: '../images/SH-310.jpg'},
        //         {name: 'SH-311', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 67.8, imgURL: '../images/SH-311.jpg'},
        //         {name: 'SH-312', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 37.2, imgURL: '../images/SH-312.jpg'},
        //         {name: 'SH-313', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 40.5, imgURL: '../images/SH-313.jpg'},
        //         {name: 'SH-326', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 98.7, imgURL: '../images/SH-326.jpg'},
        //         {name: 'SH-327', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 110.4, imgURL: '../images/SH-327.jpg'},
        //         {name: 'SH-328', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 86.7, imgURL: '../images/SH-328.jpg'},
        //         {name: 'SH-329', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 97.5, imgURL: '../images/SH-329.jpg'},
        //         {name: 'SH-330', description: 'Wandwasserhahn', category: 'wandwasserhahn', colors: ['silver'], price: 108, imgURL: '../images/SH-330 SILVER.jpg'},
        //         {name: 'SH-330', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 120, imgURL: '../images/SH-330.jpg'},
        //         {name: 'SH-334', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 59.1, imgURL: '../images/SH-334.jpg'},
        //         {name: 'SH-353', description: 'Wandwasserhahn', category: 'wandwasserhahn', price: 54.6, imgURL: '../images/SH-353.jpg'},
        //     ]
        // },
        wasserhahn: {
            products: [
                {name: 'SH-109', description: 'Wasserhahn', category: 'wasserhahn', price: 15, imgURL: '../images/SH-109.jpg'},
                {name: 'SH-110', description: 'Wasserhahn', category: 'wasserhahn', price: 24, imgURL: '../images/SH-110.jpg'},
                {name: 'SH-111', description: 'Wasserhahn', category: 'wasserhahn', price: 15, imgURL: '../images/SH-111.jpg'},
                {name: 'SH-112', description: 'Wasserhahn', category: 'wasserhahn', price: 27, imgURL: '../images/SH-112.jpg'},
                {name: 'SH-114', description: 'Wasserhahn', category: 'wasserhahn', price: 27, imgURL: '../images/SH-114.jpg'},
                {name: 'SH-115', description: 'Wasserhahn', category: 'wasserhahn', price: 27, imgURL: '../images/SH-115.jpg'},
                {name: 'SH-116', description: 'Wasserhahn', category: 'wasserhahn', price: 30, imgURL: '../images/SH-116.jpg'},
                {name: 'SH-125', description: 'Wasserhahn', category: 'wasserhahn', price: 63, imgURL: '../images/SH-125.jpg'},
                {name: 'SH-127', description: 'Wasserhahn', category: 'wasserhahn', price: 19.5, imgURL: '../images/SH-127.jpg'},
                {name: 'SH-132', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-132.jpg'},
                {name: 'SH-138', description: 'Wasserhahn', category: 'wasserhahn', price: 36, imgURL: '../images/SH-138.jpg'},
                {name: 'SH-140', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-140.jpg'},
                {name: 'SH-141', description: 'Wasserhahn', category: 'wasserhahn', price: 30, imgURL: '../images/SH-141.jpg'},
                {name: 'SH-145', description: 'Wasserhahn', category: 'wasserhahn', price: 42, imgURL: '../images/SH-145.jpg'},
                {name: 'SH-146', description: 'Wasserhahn', category: 'wasserhahn', price: 48, imgURL: '../images/SH-146.jpg'},
                {name: 'SH-148', description: 'Wasserhahn', category: 'wasserhahn', price: 48, imgURL: '../images/SH-148.jpg'},
                {name: 'SH-149', description: 'Wasserhahn', category: 'wasserhahn', price: 51, imgURL: '../images/SH-149.jpg'},
                {name: 'SH-158', description: 'Wasserhahn', category: 'wasserhahn', colors: ['black', 'green', 'grey','orange', 'purple', 'red', 'white', 'yellow'], price: 36, imgURL: '../images/SH-158.jpg'},
                {name: 'SH-161', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-161.jpg'},
                {name: 'SH-162', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-162.jpg'},
                {name: 'SH-163', description: 'Wasserhahn', category: 'wasserhahn', price: 48, imgURL: '../images/SH-163.jpg'},
                {name: 'SH-164', description: 'Wasserhahn', category: 'wasserhahn', colors: ['grey'], price: 55.2, imgURL: '../images/SH-164.jpg'},
                {name: 'SH-165', description: 'Wasserhahn', category: 'wasserhahn', colors: ['black', 'white'], price: 32.1, imgURL: '../images/SH-165.jpg'},
                {name: 'SH-166', description: 'Wasserhahn', category: 'wasserhahn', price: 45, imgURL: '../images/SH-166.jpg'},
                {name: 'SH-175', description: 'Wasserhahn', category: 'wasserhahn', price: 54, imgURL: '../images/SH-175.jpg'},
                {name: 'SH-192', description: 'Wasserhahn', category: 'wasserhahn', price: 53.7, imgURL: '../images/SH-192.jpg'},
                {name: 'SH-193', description: 'Wasserhahn', category: 'wasserhahn', price: 53.4, imgURL: '../images/SH-193.jpg'},
                {name: 'SH-194', description: 'Wasserhahn', category: 'wasserhahn', price: 53.4, imgURL: '../images/SH-194.jpg'},
                {name: 'SH-195', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-195.jpg'},
                {name: 'SH-196', description: 'Wasserhahn', category: 'wasserhahn', price: 75, imgURL: '../images/SH-196.jpg'},
                {name: 'SH-197', description: 'Wasserhahn', category: 'wasserhahn', price: 81, imgURL: '../images/SH-197.jpg'},
                {name: 'SH-198', description: 'Wasserhahn', category: 'wasserhahn', price: 36, imgURL: '../images/SH-198.jpg'},
                {name: 'SH-199', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-199.jpg'},
                {name: 'SH-208', description: 'Wasserhahn', category: 'wasserhahn', price: 60, imgURL: '../images/SH-208.jpg'},
                {name: 'SH-209', description: 'Wasserhahn', category: 'wasserhahn', price: 66, imgURL: '../images/SH-209.jpg'},
                {name: 'SH-210', description: 'Wasserhahn', category: 'wasserhahn', price: 66, imgURL: '../images/SH-210.jpg'},
                {name: 'SH-212', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-212.jpg'},
                {name: 'SH-213', description: 'Wasserhahn', category: 'wasserhahn', price: 111, imgURL: '../images/SH-213.jpg'},
                {name: 'SH-214', description: 'Wasserhahn', category: 'wasserhahn', price: 117, imgURL: '../images/SH-214.jpg'},
                {name: 'SH-215', description: 'Wasserhahn', category: 'wasserhahn', price: 61.5, imgURL: '../images/SH-215.jpg'},
                {name: 'SH-218', description: 'Wasserhahn', category: 'wasserhahn', price: 69, imgURL: '../images/SH-218.jpg'},
                {name: 'SH-229', description: 'Wasserhahn', category: 'wasserhahn', price: 156, imgURL: '../images/SH-229.jpg'},
                {name: 'SH-233', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-233.jpg'},
                {name: 'SH-235', description: 'Wasserhahn', category: 'wasserhahn', price: 36, imgURL: '../images/SH-235.jpg'},
                {name: 'SH-236', description: 'Wasserhahn', category: 'wasserhahn', price: 30, imgURL: '../images/SH-236.jpg'},
                {name: 'SH-237', description: 'Wasserhahn', category: 'wasserhahn', price: 87, imgURL: '../images/SH-237.jpg'},
                {name: 'SH-238', description: 'Wasserhahn', category: 'wasserhahn', price: 93, imgURL: '../images/SH-238.jpg'},
                {name: 'SH-239', description: 'Wasserhahn', category: 'wasserhahn', price: 30, imgURL: '../images/SH-239.jpg'},
                {name: 'SH-240', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-240.jpg'},
                {name: 'SH-241', description: 'Wasserhahn', category: 'wasserhahn', price: 57, imgURL: '../images/SH-241.jpg'},
                {name: 'SH-249', description: 'Wasserhahn', category: 'wasserhahn', price: 83.75, imgURL: '../images/SH-249.jpg'},
                {name: 'SH-255', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-255.jpg'},
                {name: 'SH-256', description: 'Wasserhahn', category: 'wasserhahn', price: 38.4, imgURL: '../images/SH-256.jpg'},
                {name: 'SH-261', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-261.jpg'},
                {name: 'SH-262', description: 'Wasserhahn', category: 'wasserhahn', price: 39, imgURL: '../images/SH-262.jpg'},
                {name: 'SH-269', description: 'Wasserhahn', category: 'wasserhahn', price: 42.3, imgURL: '../images/SH-269.jpg'},
                {name: 'SH-270', description: 'Wasserhahn', category: 'wasserhahn', price: 42, imgURL: '../images/SH-270.jpg'},
                {name: 'SH-275', description: 'Wasserhahn', category: 'wasserhahn', price: 27, imgURL: '../images/SH-275.jpg'},
                {name: 'SH-276', description: 'Wasserhahn', category: 'wasserhahn', price: 36, imgURL: '../images/SH-276.jpg'},
                {name: 'SH-278', description: 'Wasserhahn', category: 'wasserhahn', price: 36, imgURL: '../images/SH-278.jpg'},
                {name: 'SH-283', description: 'Wasserhahn', category: 'wasserhahn', price: 90, imgURL: '../images/SH-283.jpg'},
                {name: 'SH-284', description: 'Wasserhahn', category: 'wasserhahn', price: 81, imgURL: '../images/SH-284.jpg'},
                {name: 'SH-288', description: 'Wasserhahn', category: 'wasserhahn', price: 10.5, imgURL: '../images/SH-288.jpg'},
                {name: 'SH-290', description: 'Wasserhahn', category: 'wasserhahn', price: 27, imgURL: '../images/SH-290.jpg'},
                {name: 'SH-291', description: 'Wasserhahn', category: 'wasserhahn', price: 96, imgURL: '../images/SH-291.jpg'},
                {name: 'SH-292', description: 'Wasserhahn', category: 'wasserhahn', price: 66.9, imgURL: '../images/SH-292.jpg'},
                {name: 'SH-301', description: 'Wasserhahn', category: 'wasserhahn', price: 45, imgURL: '../images/SH-301.jpg'},
                {name: 'SH-302', description: 'Wasserhahn', category: 'wasserhahn', price: 93, imgURL: '../images/SH-302.jpg'},
                {name: 'SH-308', description: 'Wasserhahn', category: 'wasserhahn', price: 42.6, imgURL: '../images/SH-308.jpg'},
                {name: 'SH-309', description: 'Wasserhahn', category: 'wasserhahn', price: 42, imgURL: '../images/SH-309.jpg'},
                {name: 'SH-314', description: 'Wasserhahn', category: 'wasserhahn', price: 42, imgURL: '../images/SH-314.jpg'},
                {name: 'SH-321', description: 'Wasserhahn', category: 'wasserhahn', price: 76.5, imgURL: '../images/SH-321.jpg'},
                {name: 'SH-322', description: 'Wasserhahn', category: 'wasserhahn', price: 69.9, imgURL: '../images/SH-322.jpg'},
                {name: 'SH-340', description: 'Wasserhahn', category: 'wasserhahn', price: 24, imgURL: '../images/SH-340.jpg'},
                {name: 'SH-344', description: 'Wasserhahn', category: 'wasserhahn', price: 84, imgURL: '../images/SH-344.jpg'},
                {name: 'SH-346', description: 'Wasserhahn', category: 'wasserhahn', price: 33, imgURL: '../images/SH-346.jpg'},
                {name: 'SH-347', description: 'Wasserhahn', category: 'wasserhahn', price: 31.5, imgURL: '../images/SH-347.jpg'},
                {name: 'SH-348', description: 'Wasserhahn', category: 'wasserhahn', price: 84, imgURL: '../images/SH-348.jpg'},
                {name: 'SH-366', description: 'Wasserhahn', category: 'wasserhahn', price: 35.7, imgURL: '../images/SH-366.jpg'},
                {name: 'SH-367', description: 'Wasserhahn', category: 'wasserhahn', price: 35.7, imgURL: '../images/SH-367.jpg'},
                {name: 'SH-368', description: 'Wasserhahn', category: 'wasserhahn', price: 41.4, imgURL: '../images/SH-368.jpg'},
                {name: 'SH-369', description: 'Wasserhahn', category: 'wasserhahn', price: 38.7, imgURL: '../images/SH-369.jpg'},
                {name: 'SH-373', description: 'Wasserhahn', category: 'wasserhahn', price: 35.4, imgURL: '../images/SH-373.jpg'},
                {name: 'MH-11035', description: 'WASserhahn Mischer Schlauch', category: 'wasserhahn', price: 7.32, imgURL: '../images/MH-11035.jpg'},
                {name: 'MH-11075', description: 'WASserhahn Mischer Schlauch', category: 'wasserhahn', price: 8.85, imgURL: '../images/MH-11075.jpg'},
                {name: 'WH-31020', description: 'WASserhahn Mischer Schlauch', category: 'wasserhahn', price: 4.5, imgURL: '../images/WH-31020.jpg'},
                {name: 'WH-31075', description: 'WASserhahn Mischer Schlauch', category: 'wasserhahn', price: 6, imgURL: '../images/WH-31075.jpg'},
            ],
        }
    }
}

export default data;